from bot.keyboards.default_kb import (
    BTN_ADMIN,
    BTN_BECOME_DRIVER,
    BTN_CARGO,
    BTN_CANCEL,
    BTN_GUZOR_TASHKENT,
    BTN_MAIN,
    BTN_MY_TRIPS,
    BTN_POST_RETURN,
    BTN_PROFILE,
    BTN_RETURN_TRIPS,
    BTN_SUBSCRIBE,
    BTN_TAXI,
    BTN_TASHKENT_GUZOR,
    contact_keyboard,
    main_menu,
)
from bot.keyboards.inline_kb import claim_order_kb

__all__ = [
    "BTN_TAXI",
    "BTN_GUZOR_TASHKENT",
    "BTN_TASHKENT_GUZOR",
    "BTN_RETURN_TRIPS",
    "BTN_CARGO",
    "BTN_BECOME_DRIVER",
    "BTN_POST_RETURN",
    "BTN_MY_TRIPS",
    "BTN_PROFILE",
    "BTN_SUBSCRIBE",
    "BTN_ADMIN",
    "BTN_CANCEL",
    "BTN_MAIN",
    "main_menu",
    "contact_keyboard",
    "claim_order_kb",
]
